### ISSUE TITLE
Missing opening XML tag

### ISSUE THREAD

**Issue by arc95** [sinairv/YAXLib#101]
Hi @sinairv. Thanks for this library. One thing we're struggling with is the missing opening XML tag when we serialize a class. So the serialized object string is missing this:

`<?xml version="1.0" encoding="utf-8"?>`

We use this to serialize the object:

```
var yaxSerializer = new YAXSerializer(typeof(SomeClass));
return yaxSerializer.Serialize(SomeObject);
```

Thanks.

**Comment by 304NotModified** [comment]
You mean the "XML preamble", isn't?

**Comment by arc95** [comment]
Yes, preamble.

**Comment by 304NotModified** [comment]
AFAIK you need to concatenate it yourself. Anyway, it's always the same string ;)

**Comment by arc95** [comment]
Thanks, @304NotModified
