### ISSUE TITLE
Add Bin/*.dll.mdb to .gitignore

### ISSUE THREAD

**Issue by silwol** [sinairv/YAXLib#23]
When including YAXLib source tree into a project of mine and building it, the file Bin/YAXLib.dll.mdb is generated which is not ignored by git. It would make sense to ignore the Bin/*.dll.mdb pattern in .gitignore.

**Comment by 304NotModified** [comment]
it this is fixed already? 

https://github.com/sinairv/YAXLib/blob/master/.gitignore#L15

**Comment by sinairv** [comment]
Yes it is. Closing it now. Thanks.
