### ISSUE TITLE
proposal: remove old solution files

### ISSUE THREAD

**Issue by 304NotModified** [sinairv/YAXLib#40]
Proposal to remove the old solution files and only keep `YAXLib.2013.sln`. I don't see any benefit (or am I missing somthing?). You can open `YAXLib.2013.sln` also in VS2012. 

The downside of multiple solution files is to keep them all in-sync. 

to be removed:
 - YAXLib.2008.sln 	
 - YAXLib.2010.sln 	
 - YAXLib.2012.sln

**Comment by sinairv** [comment]
This is just historic, and doesn't serve any technical purposes, even though many people may still have access to older versions of VS (for pricing or work place policies, etc). Since the solution is a link to only a couple of projects I see the headache of keeping the solutions in sync as minimal.

**Comment by 304NotModified** [comment]
Agree. Only the Solution files are duplicate, not the project files. 

Thanks for responding!
