### ISSUE TITLE
Publish 2.14 on Nuget

### ISSUE THREAD

**Issue by 304NotModified** [sinairv/YAXLib#44]
[changelog](https://github.com/sinairv/YAXLib/blob/master/ChangeLog.md) talks about 2.14, but the latest version on Nuget is 2.13

![image](https://cloud.githubusercontent.com/assets/5808377/12298190/1f50772a-ba11-11e5-95b1-9ed41dc9cee7.png)

**Comment by sinairv** [comment]
That's right. I used to usually wait for a few bug fixes to accumulate and then do a release.

**Comment by sinairv** [comment]
Just published 2.14
