### ISSUE TITLE
Crash when serialize a dictionary with a null value

### ISSUE THREAD

**Issue by Rowandish** [sinairv/YAXLib#45]
I find the following bug in the YAXLib source code:

If I try to serialize a dictionary that contains a null value I got a unhandled `nullReference` exception.

    Dictionary<string, object> Dict= new Dictionary<string, object>();
    Dict.Add("foo", null);
    YAXSerializer serializer = new YAXSerializer(typeof (Dictionary<string, object>));
    _serializer.SerializeToFile(Dict, "path"); // << CRASH

Running deep in YAXSerializer.cs I found the following code:

    foreach (object obj in dicInst) //dicInst is the Dict variable defined above
    {
      ...
      // valueObj is null
      XElement addedElem = AddObjectToElement(elemChild, valueAlias, valueObj);
      ...
    }
    
    private XElement AddObjectToElement(XElement elem, XName alias, object obj)
    {
      //obj is null and so obj.GetType() crash
      UdtWrapper udt = TypeWrappersPool.Pool.GetTypeWrapper(obj.GetType(), this);
      ...
    }

Am I missing something?
How to handle this problem?
Thanks! :)

**Comment by sinairv** [comment]
Has been fixed in the source code, will publish the nuget shortly as well. You can clone and check the master branch, to make sure if it's been fixed. Thanks.
