### ISSUE TITLE
Is code generation among the features?

### ISSUE THREAD

**Issue by beppe9000** [sinairv/YAXLib#51]
I would like to generate classes from xsd or wsdl files.

**Comment by sinairv** [comment]
I'm afraid it's not supported.

**Comment by beppe9000** [comment]
Thanks for the information. Do you recommend any other library (free/open source) with this feature?

**Comment by 304NotModified** [comment]
You can do it with visual studio?

**Comment by beppe9000** [comment]
Yes, I use visual Studio

**Comment by 304NotModified** [comment]
http://stackoverflow.com/questions/5217665/how-to-generate-net-4-0-classes-from-xsd

**Comment by beppe9000** [comment]
The xsd tool fails with the CWMP spec xsd
