### ISSUE TITLE
SerializeAs using YAXSerializeAs attribute replace ":" by "_"

### ISSUE THREAD

**Issue by Nordes** [sinairv/YAXLib#66]
Hi,

Maybe it is me who's not using the library properly. But I was wondering why the ":" was replaced by "_" while doing the serialization?

Example
```
        [YAXCollection(YAXCollectionSerializationTypes.Recursive, EachElementName = "zone:name")]
        [YAXSerializeAs("zone:list")]
        public List<string> Zones { get; set; }
```

I will see the XML output as "zone_list" and "zone_name".

Thank you

**Comment by Nordes** [comment]
BTW in the library code you can see the following:
```
        private static bool IsValidNameStartChar(char ch)
        {
            // This uses the rules defined in http://www.w3.org/TR/xml/#NT-Name. 
            // However colon (:) has been removed from the set of allowed characters,
            // because it is reserved for separating namespace prefix and XML-entity names.
            if (//ch == ':' || 
                ch == '_' ||
```

So how do I get the proper serialization then ?

**Comment by sinairv** [comment]
As you mentioned per comment in the code, `:` is not allowed in element/attribute names in the XML standard. I believe what you are after is an XML namespace. 

    [YAXCollection(YAXCollectionSerializationTypes.Recursive, EachElementName = "{http://namespaces.org/zone_or_whatever_url}name")]
    [YAXSerializeAs("list")]
    [YAXNamespace("zone", "http://namespaces.org/zone_or_whatever_url")]
    public List<string> Zones { get; set; }

Note that when it comes to namespaces, it's the URL that identifies them.

**Comment by Nordes** [comment]
I'll try. It's because I wanted to use YAXLib with a bad xml API and they don't declare any namespace... they just put the element like they wish using/abusing the namespace notation.

**Comment by Nordes** [comment]
After a few tests it worked :) thank's a lot. 

Regarding the YAXNamespace, I don't recall seeing it in your demo/article. Maybe having a small wiki could help ;). Thank's again
