### ISSUE TITLE
"Porting" to .NET Standard

### ISSUE THREAD

**Issue by LabInfoRosselli** [sinairv/YAXLib#90]
Hi,
since you have upgraded your project to .NET Core, why you don't do a "definitive" step and create a .NET Standard library ?
Thanks in advance

**Comment by 304NotModified** [comment]
it already supports .NET Standard 1.6?



![image](https://user-images.githubusercontent.com/5808377/38801516-4e986b54-416a-11e8-9841-05181f5e3b4e.png)

https://www.nuget.org/packages/YAXLib/

**Comment by 304NotModified** [comment]
Although i'm a bit confused, the project- (csproj) and solution file aren't VS2017+.NET standard?

**Comment by LabInfoRosselli** [comment]
Hi, i'm sorry but reading in the title "..Serialization Library for the .NET Framework and .NET Core" i assumed that there was not a .NET standard version.
Sorry again for my mistake and thanks for your work.

**Comment by LabInfoRosselli** [comment]
Hi, i'm sorry but reading in the title "..Serialization Library for the .NET Framework and .NET Core" i assumed that there was not a .NET standard version.
Sorry again for my mistake and thanks for your work.
